### ISSUE TITLE
Compiled with problems:ERROR in src/api/ajax.ts:67:5

### ISSUE THREAD

**Issue by sgpfei** [feihua/salvo-admin-ui#1]
Compiled with problems:
ERROR in src/api/ajax.ts:67:5
TS2345: Argument of type '(config: AxiosRequestConfig) => AxiosRequestConfig<any>' is not assignable to parameter of type '(value: InternalAxiosRequestConfig<any>) => InternalAxiosRequestConfig<any> | Promise<InternalAxiosRequestConfig<any>>'.
  Type 'AxiosRequestConfig<any>' is not assignable to type 'InternalAxiosRequestConfig<any> | Promise<InternalAxiosRequestConfig<any>>'.
    Type 'AxiosRequestConfig<any>' is not assignable to type 'InternalAxiosRequestConfig<any>'.
      Types of property 'headers' are incompatible.
        Type 'AxiosHeaders | (Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }> & Partial<...>) | undefined' is not assignable to type 'AxiosRequestHeaders'.
          Type 'undefined' is not assignable to type 'AxiosRequestHeaders'.
            Type 'undefined' is not assignable to type 'Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>'.
    65 | // axios实例拦截请求
    66 | axiosInstance.interceptors.request.use(
  > 67 |     (config: AxiosRequestConfig) => {
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    68 |         const token = storageUtils.getToken()
    69 |         if (token) {
    70 |             // @ts-ignore
![Snipaste_2024-09-18_11-33-03](https://github.com/user-attachments/assets/d3223ab0-7183-4035-9200-68bc5d828824)

**Comment by feihua** [comment]
已修复
